---
title: "Project Summary"
author: "Niraj Juneja, Charles de Lassence"
output: rmarkdown::html_document
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Fitcoach project summary

We are glad to submit the fitcoach package. As part of the project we have been able to accomplish the following:

1. Connect R to Fitbit API and expose an individual’s Fitbit data as a Dataframe for further analysis.
    + DataLoader.R does this. __[Example 1 shows how to do this](examples\fitcoach-usage.html)__
    + DataLoader enables getting both the *Daily time-series* data and *Intra-day time-series* data at 15 min breaks for the individual. 
    + Note : intra-day data will require the user to create a new app on Fitbit website and is only available for app owner. i.e User A cannot access Intra-day data from User B. This is a Fitbit restriction

2. Created [FitAnalyzer R6](..\R\FitAnalyzer.R) class that provides an __opinionated__ but focussed implementation for analyzing Fitbit Data. It is likely that this workflow might not work for all. In this situation, the user can directly use Fitbit functions provided in [FitUtil.R](..\R\FitUtil.R)  and create a customized analysis flow. 

3. In line with the project proposal, we were able to build the following.
  + Ability to set goals and find the most significant variables that are enabling meeting the goals. The [Example 2 and Example 3 here](examples\fitcoach-usage.html) demonstrates this flow. 
  + Ability to call a function and provide recommendations for the rest of the day. The [Example 2 and 3](examples\fitcoach-usage.html) demonstrate this flow. This is implemented for both daily and intra-day scenarios.
  + Provide advanced charts in ggplot2. The [Example 2 and Example 3 here](examples\fitcoach-usage.html) demonstrate the graphs.
  
4. Package Design Philosophy
  + DataLoader.R is an R6 class because it encapsulates a unique OAuth2.0 based flow for accessing Fitbit API. The goal of this class is to orchestrate the Fitbit connection flow and download __daily__ or __intraday__ json files into a folder so that the json files can be analyzed further.
  + FitAnalyzer.R is an R6 class with a opinioned workflow for analysis. The class maintains state related to goal, analysis type among other things. It does not store the data.frame used for analysis to avoid memory issues. The user is expected to hold on to the data.frame
  + FitUtil.R is a utility file that has functions for Fitbit analysis. 
  + We are using [GLM](https://stat.ethz.ch/R-manual/R-devel/library/stats/html/glm.html) for daily file and [GBM](https://cran.r-project.org/web/packages/gbm/gbm.pdf) for intraday file analysis. intra-day file analysis has a lot more data points and hence GBM works well here.For daily file, we have 1 datapoint per day. Hence, we decided to use GLM because we do not expect a lot of data in this file.
  
__Please refer to the detailed [Example ](examples\fitcoach-usage.html) to understand the usage of the package__
